### ISSUE TITLE
Configuration Issue : plugin not working

### ISSUE THREAD

**Issue by VoSu** [mibexsoftware/sonar-bitbucket-plugin#101]
### Expected Behavior

I'm expected to have the ability to review analysis coming from SonarQube coupled to Bitbucket as I've some PRs opened...

### Actual Behavior

This is what I can see as an output

INFO: ANALYSIS SUCCESSFUL
INFO: Executing post-job Sonar Plug-in for Bitbucket Cloud

INFO: [sonar4bitbucket] No open pull requests with source branch 'feature/release_1.2.2' found. No analysis will be performed..

Same at bitbucket level, I'm not able to review the Sonar output : 

<img width="422" alt="capture d ecran 2019-02-16 a 23 05 50" src="https://user-images.githubusercontent.com/2857559/52905788-8956b400-323f-11e9-9bed-3889f49dbbdb.png">

### Plug-in version, SonarQube version, CI system, build type

Instances used :
- Bitbucket Cloud
- SonarQube 6.4
- Sonar4Bitbucket 1.2.3
- Jenkins 2.150.2

Configuration used : 

-Dsonar.bitbucket.repoSlug=project \
-Dsonar.bitbucket.accountName=bitbucket repo \
-Dsonar.bitbucket.oauthClientKey=client key created under my user as I'm admin of the bitbucket repo \
-Dsonar.bitbucket.oauthClientSecret=client secret \
-Dsonar.bitbucket.branchName=${gitBranch} \
-Dsonar.sourceEncoding=UTF-8 \
-Dsonar.bitbucket.branchIllegalCharReplacement=- \
-Dsonar.bitbucket.approvalFeatureEnabled=true \
-Dsonar.bitbucket.buildStatusEnabled=true \
-Dsonar.analysis.mode=issues"

I followed all the step coming from that link [https://mibexsoftware.atlassian.net/wiki/spaces/SONAR4BB/pages/22872072/Installation](url)

I'm a bit struggled by the fact that I've no clue on what's going on as I'm pretty sure that I followed each step to configure the plugin properly

Can you plz guide me on what's going on ?

**Comment by rhaex** [comment]
Are you sure that you have a pull-request in BitBucket with source branch **feature/release_1.2.2**?
To get comments on a pull-request in BitBucket, you have to checkout the same branch as the one specified as source in the pull-request, then run SonarQube plugin.

**Comment by VoSu** [comment]
@rhaex the branch was released from the time that I wrote to start that thread.

Anyway, I did it on some new branches and now, it's working properly.

Thank you for your time and your answer.
