### ISSUE TITLE
Plugin doesn't work with SonarQube 7.7 due to deprecated sonar.analysis.mode option

### ISSUE THREAD

**Issue by ramon-b** [mibexsoftware/sonar-bitbucket-plugin#104]
### Expected Behavior

I expect that I can use SonarQube 7.7 in combination with this plugin without errors when executing a scan.

### Actual Behavior

The sonar.analysis.mode option is deprecated (see https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/132), but required by this plugin. If I try to execute a scan with -Dsonar.analysis.mode=issues or -Dsonar.analysis.mode=preview, I receive this error:
```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 0.979s
INFO: Final Memory: 12M/362M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: The preview mode, along with the 'sonar.analysis.mode' parameter, is no more supported. You should stop using this parameter.
```

Without the option set, I receive this error:

```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 1.378s
INFO: Final Memory: 15M/306M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Failed to execute project builder: ch.mibex.bitbucket.sonar.review.PullRequestProjectBuilder
ERROR: Caused by: requirement failed: [sonar4bitbucket] The plug-in only works in preview or issues mode. Please set "-Dsonar.analysis.mode" accordingly.
```

### Plug-in version, SonarQube version, CI system, build type

Plug-in version: 1.3.0 (build from master branch)
SonarQube version: 7.7
CI system: Jenkins 2.138.2

**Comment by aetorres** [comment]
Hi *, 

I have the same issue.

I'm working with 

Plug-in version: 1.3.0 (build from master branch)
SonarQube version: 7.7 Community Edition
CI system: Jenkins 2.148
SonarQube Scanner version: 3.2.0.1227
Maven version: 3.5.3
Java Version:  Java 1.8.201

**Comment by oliemansm** [comment]
Same here. Seems related or caused by #81. Is anybody working on or planning to work on a solution for this any time soon? I see #81 is open for a year already now.

**Comment by FelikZ** [comment]
Same here

**Comment by rady66** [comment]
it is a bit annoying. hopefully, that will be resolved soon...

**Comment by mrueegg** [comment]
Hi. Please excuse my late response. I'm going to tackle this in the next few days. Thanks in advance for your patience!

**Comment by lukaszun** [comment]
@mrueegg  - any progress on this?

**Comment by mrueegg** [comment]
Hi all,

We analyzed this and unfortunately, we cannot support SonarQube versions >= 7.7 anymore because of the removed preview mode.

Thank you for your understanding.

Best regards,
Michael

**Comment by elinalin** [comment]
Does anyone know how to make this preview mode work?

**Comment by Nedlinin** [comment]
To clarify, this plugin is essentially dead then as no future versions are intended to be supported?

**Comment by sudo-plz** [comment]
The problem might not be as big as it seems, looking over at the Gitlab plugin, they fixed it using the SonarQube Community edition with Sonar community branch plugin installed or SonarQube Developer edition.

https://github.com/gabrie-allaigre/sonar-gitlab-plugin/pull/253
