### ISSUE TITLE
Plugin will stop working from 29.04 

### ISSUE THREAD

**Issue by wasikuss** [mibexsoftware/sonar-bitbucket-plugin#105]
According to https://confluence.atlassian.com/bitbucket/version-1-423626337.html BitBucket will stop supporting API v1 on 29.04. All calls should use v2.

**Comment by wasikuss** [comment]
sorry didn't saw #92 before. but it's already 18th. Will pr be merged soon?

**Comment by mrueegg** [comment]
@wasikuss Please excuse my late response. I'm going to tackle this in the next few days. Thanks in advance for your patience!

**Comment by mrueegg** [comment]
@wasikuss I've just merged #92.

Best regards,
Michael
