### ISSUE TITLE
call back URL in the Bitbucket OAuth configuration for sonar plugin

### ISSUE THREAD

**Issue by raghav-a** [mibexsoftware/sonar-bitbucket-plugin#106]
while running the command 

mvn clean verify sonar:sonar --batch-mode --errors \
                        -Dsonar.bitbucket.repoSlug=<slug> \
                        -Dsonar.bitbucket.accountName=<account> \
                        -Dsonar.bitbucket.teamName=<team> \
                        -Dsonar.bitbucket.oauthClientKey=<key> \
                        -Dsonar.bitbucket.oauthClientSecret=<secret> \
                        -Dsonar.bitbucket.branchName=<branch> \
                        -Dsonar.host.url=<sonar.url> \
                        -Dsonar.login=<uname> \
                        -Dsonar.password=<pwd> \
                        -Dsonar.analysis.mode=issues

I am using oauth for authentication with bitbucket and added 

I m getting the error

**Caused by: java.lang.IllegalStateException: [sonar4bitbucket] Could not create an OAuth access token:
No callback uri defined for the OAuth client.
Have you defined a callback URL in the Bitbucket OAuth configuration?**

I did see an option of adding a call back uri while creating oauth consumer in bitbucket cloud 
but what should be the value of this **call back URI** ????

### Plug-in version, SonarQube version, CI system, build type
sonarqube version 6.7.4

**Comment by mrueegg** [comment]
@raghav-a Please excuse my late response. The callback URI can have any value, it's just important that it is configured. I'll update the documentation in this regard.
