### ISSUE TITLE
Make accept on passing optional

### ISSUE THREAD

**Issue by Kostronor** [mibexsoftware/sonar-bitbucket-plugin#11]
Context:
We have to use OAuth of the repo owners account and the plugin accepts all pull requests when the build passes in his name. Something surely not intended. Please make a config option to let us choose if we want this feature or not.

**Comment by cltnschlosser** [comment]
Just to verify, the pull request is approved (not merged), also this is on bitbucket.

**Comment by mrueegg** [comment]
So just to see if I got you right: you want to have the possibility to configure if the plug-in approves / unapproves the pull request in case no blocker or critical issues are found? I can surely do this.

**Comment by Kostronor** [comment]
We just want to disable it completely. Because then it diffuses between the plugin and his decision.

**Comment by mrueegg** [comment]
Okay, so I will create a new option "sonar.bitbucket.approvalFeatureEnabled" for this. I should be able to implement this in the next few days.

**Comment by Kostronor** [comment]
thanks a lot, will add it to the script now and update soon :+1:

**Comment by damianroszyk** [comment]
Hi, could you make an option to configure approval/non approval for major issues? For now plugin comments pull requests but also accepts it. Thanks in advance!

**Comment by mrueegg** [comment]
@damianroszyk The plug-in only accepts the pull request if there are no blocker and critical issues. 

Do you need something else than the mentioned new configuration option to disable approving/unapproving of pull requests?

**Comment by damianroszyk** [comment]
It would be nice if plugin does not accept pull requests that have major issues also ( major + blocker + critical = 0)

**Comment by mrueegg** [comment]
@damianroszyk I think blocker and critical issues are clear, but major issues can be debatable. So I guess I would have to make this configurable then... What do you think?

**Comment by damianroszyk** [comment]
@mrueegg configurable option for major issues accept is ok with me, thanks

**Comment by mrueegg** [comment]
@damianroszyk Optional approval feature is implemented. Could you please create a new issue for the configurable issue severities feature?
