### ISSUE TITLE
Report only shows issues of current commit

### ISSUE THREAD

**Issue by Kostronor** [mibexsoftware/sonar-bitbucket-plugin#13]
For example:

We have a PR with 5 major and one minor issue.

Someone updated the PR to fix the minor one.

`SonarQube Analysis reported no issues. Take a chocolate :-)` And all issues are deleted.

What is really needed:

A report of all issues at lines changed in the PR diff. Or a report for every commit individually. Or both ;)

**Comment by mrueegg** [comment]
Hi,

This is of course not the intended behaviour. You should get a report with 5 major issues instead. Did this only happen once or is it reproducible? Have you seen any errors in your build log from the SonarQube plug-in?

**Comment by Kostronor** [comment]
There is no error, no printout (I'm not running verbose) and is always reproducible. 
All build logs _should_ be public here http://home.kk-sc.de:8085/browse/MINECOL-JAR
PRs are viewable here https://bitbucket.org/cltnschlosser/minecolonies/pull-requests/
Old comments sadly get deleted
Sonarcube is here http://home.kk-sc.de:9000/
More stuff needed to reproduce: marvin@marv-productions.de :)

**Comment by mrueegg** [comment]
Thanks. To be able to troubleshoot this, could you please run the plug-in with debug logging enabled?

mvn sonar:sonar -X -Dsonar.verbose=true ...

**Comment by Kostronor** [comment]
Well first it didn't spit out anything more. And after I added debug output to gradle it littered the OAuth token everywhere. Not nice ;)
https://www.dropbox.com/s/xoku18gfdy2467m/buildlog.txt?dl=0
It is a bit long btw ;)

**Comment by mrueegg** [comment]
Thanks for the log. You are right, when the requests get logged we should try to obfuscate all credentials in there. I opened #14 for this.

**Comment by Kostronor** [comment]
Any news on this issue?

**Comment by Kostronor** [comment]
Not fixed!

**Comment by Kostronor** [comment]
Thanks for the commit, will check out if this fixes our issues :-)

**Comment by MichaelRueegg** [comment]
@Kostronor I fixed issues related to the one you reported in release 1.1.3. Could you please upgrade and try again?

**Comment by Kostronor** [comment]
Sure will do! 
The first comment was because github on mobile does not show commits and it looks like a close without anything... 
Will report once we get some pr's going

**Comment by Kostronor** [comment]
Okay, now we got out first big PR going and well, not working sadly:
https://bitbucket.org/cltnschlosser/minecolonies/pull-requests/171/transition-189/diff#comment-17959250

If you need more info, please tell
