### ISSUE TITLE
Configurable option for issue accept on Pull Requests

### ISSUE THREAD

**Issue by damianroszyk** [mibexsoftware/sonar-bitbucket-plugin#16]

**Comment by mrueegg** [comment]
Hi,

Could you please describe the intent of this issue in more detail? Do you refer to the possibility to configure if the pull request should be approved/unapproved by the plug-in(see #16)?

**Comment by damianroszyk** [comment]
Hey, 
for now plugin accepts pull request if there are no CRITICAL/BLOCKER issues found.
Could you make an option to not accept pull request if there are some MAJOR issues found ?

**Comment by mrueegg** [comment]
Fixed with #54
