### ISSUE TITLE
Comments were not added to the new file!

### ISSUE THREAD

**Issue by lcasat** [mibexsoftware/sonar-bitbucket-plugin#20]
Hi,

When the pull request have a brand new file, the pulg-in is identifying the issues, the comments were not visible with the file. Instead the comments can be seen the activity tab of the bitbucket with the this message:

"commented on a file but no context is available"

![screen shot 2016-03-14 at 1 58 46 pm](https://cloud.githubusercontent.com/assets/5344745/13738873/bbca8198-e9ed-11e5-81bb-f3d230904f25.png)

**Comment by MichaelRueegg** [comment]
Hi,

Thanks for your bug report. We've just fixed this and released the new version 1.1.2. Could you please upgrade and try again?

**Comment by lcasat** [comment]
It's now working. Thanks Michael.

**Comment by MichaelRueegg** [comment]
That's good news. Thanks for your feedback!
