### ISSUE TITLE
Plugin not working as Bitbucket URL is incorrect

### ISSUE THREAD

**Issue by dkaranth** [mibexsoftware/sonar-bitbucket-plugin#21]
Plugin not working as Bitbucket URL is incorrect. In many places in the plugin code, the plugin tries to connect to the bitbucket server and uses the token "pullrequests" as part of the URL. e.g https://bitbucket.org/<user>/<project>/pullrequests?<query> params

But in the version of the cloud bitbucket that I am using, it is not "pullrequests", but instead "pull-requests" (with the hyphen).

Hence, the operations are failing to find the required resource.

**Comment by MichaelRueegg** [comment]
Hi,

I'm not aware of this. According to the [official Bitbucket REST documentation](https://confluence.atlassian.com/bitbucket/pullrequests-resource-423626332.html) it is `pullrequests`:

https://bitbucket.org/api/1.0/repositories/accountName/repoSlug/pullrequests/1/comments

What error do you get? A stack trace would help me much. Also, in your URL example, `accountName` and `repoSlug` are missing. Have you specified them in the options when you trigger the plug-in?

     -Dsonar.bitbucket.repoSlug=YOUR_BITBUCKET_REPO_SLUG \
     -Dsonar.bitbucket.accountName=YOUR_BITBUCKET_ACCOUNT_NAME \

**Comment by MichaelRueegg** [comment]
Closed as no response.
