### ISSUE TITLE
Duplicated code-level comments using OAuth

### ISSUE THREAD

**Issue by nwoolls** [mibexsoftware/sonar-bitbucket-plugin#22]
I see code in `ReviewCommentsCreator` that looks like this plugin should be updating / deleting old code-level comments as long as they are on the same line and have matching text. However, when I trigger the SonarQube analysis, the plugin keeps adding duplicated comments on the same lines as its previous comments.

Note we're using OAuth and not a team account & API key. When I use an API key there are no duplicated entries.

**Comment by mrueegg** [comment]
Please excuse my late response. Did release 1.1.7 with the fix from #33 resolve the issue for you as well?

**Comment by nwoolls** [comment]
@mrueegg I'm not sure when exactly this got fixed but we've not seen this issue in a long time. It does not happen currently and we're on 1.1.7.

**Comment by mrueegg** [comment]
@nwoolls Thanks for your feedback. I will therefore close this issue now. If it ever occurs again, please open a new one.
