### ISSUE TITLE
SonarReviewPostJob fails with NullPointerException

### ISSUE THREAD

**Issue by CyranoB** [mibexsoftware/sonar-bitbucket-plugin#28]
On a repository I have the following error.
```
INFO: 11421/11421 components tracked
INFO: ANALYSIS SUCCESSFUL
INFO: Executing post-job ch.mibex.bitbucket.sonar.review.SonarReviewPostJob
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 1:41.490s
INFO: Final Memory: 76M/2377M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1.apply(BitbucketClient.scala:83)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1.apply(BitbucketClient.scala:78)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.immutable.List.foreach(List.scala:381)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.immutable.List.map(List.scala:285)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1.apply(BitbucketClient.scala:78)
at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1.apply(BitbucketClient.scala:77)
at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:234)
at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$fetchPullRequestsPage$1(BitbucketClient.scala:76)
```

Looking at the source code, it seems the error should be cause by a non existing hash on "destination->commit->hash"

I manually checked the 114 pull requests JSON from this repository and they're all with existing hashes.
```json
{
      "description": "XXXXXXXX",
      ...
      "title": "XXXXXXX",
      "close_source_branch": true,
      "merge_commit": null,
      "destination": {
        "commit": {
          "hash": "XXXXXXXXXXX",
          "links": {
            "self": {
              "href": "https://bitbucket.org/!api/2.0/repositories/XXXXXXX"
            }
          }
        },
        ...
```

I'm not sure how to proceed further.

**Comment by MichaelRueegg** [comment]
Hi,

Could you please enable debug logging (-Dsonar.verbose=true), run the build again and attach the complete JSON output of the REST call to Bitbucket?

    mvn sonar:sonar -X -Dsonar.verbose=true ...

Thanks,
Michael

**Comment by MichaelRueegg** [comment]
Thanks for the JSON. One pull request destination branch doesn't have a commit ID:

    "destination": {
          "commit": null,

I'll have to take care of this case. Once I'll have a snapshot ready, would you be okay to test it before I release a new version?

**Comment by CyranoB** [comment]
Yes I can do that. I’m very tempted to deleted the pull request and have it
all working :)


On August 18, 2016 at 11:48:51 AM, Michael Rüegg (notifications@github.com)
wrote:

Thanks for the JSON. One pull request destination branch doesn't have a
commit ID:

"destination": {
      "commit": null,

I'll have to take care of this case. Once I'll have a snapshot ready, would
you be okay to test it before I release a new version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/28#issuecomment-240766844>,
or mute the thread

**Comment by MichaelRueegg** [comment]
Here we go. Looking forward to your test results. Thanks!

[sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/425378/sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip)

**Comment by CyranoB** [comment]
I’m now getting this:

ERROR: Error during SonarQube Scanner execution

java.lang.ClassCastException:
ch.mibex.bitbucket.sonar.client.BitbucketClient cannot be cast to
scala.collection.immutable.Map

at
ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1$$anonfun$2.apply(BitbucketClient.scala:81)

at
ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1$$anonfun$2.apply(BitbucketClient.scala:81)

at scala.Option.map(Option.scala:146)

at
ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1.apply(BitbucketClient.scala:81)

at
ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1$$anonfun$apply$1.apply(BitbucketClient.scala:78)

at
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

at
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

at scala.collection.immutable.List.foreach(List.scala:381)

at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)

at scala.collection.immutable.List.map(List.scala:285)

at
ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1.apply(BitbucketClient.scala:78)

at
ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$1.apply(BitbucketClient.scala:77)

at
ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:234)



On August 18, 2016 at 12:19:02 PM, Michael Rüegg (notifications@github.com)
wrote:

Here we go. Looking forward to your test results. Thanks!

sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip
<https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/425378/sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/28#issuecomment-240776180>,
or mute the thread

**Comment by MichaelRueegg** [comment]
Thanks for your feedback. I've fixed that issue too. Could you please try again with the attached SNAPSHOT? 

[sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip](https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/426684/sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip)

**Comment by CyranoB** [comment]
Thanks, this is now working great.

On August 19, 2016 at 5:20:32 AM, Michael Rüegg (notifications@github.com)
wrote:

Thanks for your feedback. I've fixed that issue too. Could you please try
again with the attached SNAPSHOT?

sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip
<https://github.com/mibexsoftware/sonar-bitbucket-plugin/files/426684/sonar-bitbucket-plugin-1.1.5-SNAPSHOT.jar.zip>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/28#issuecomment-240970224>,
or mute the thread

**Comment by MichaelRueegg** [comment]
That's great news, thanks for your feedback!
