### ISSUE TITLE
Support of bitbucket server

### ISSUE THREAD

**Issue by kingoleg** [mibexsoftware/sonar-bitbucket-plugin#29]
Hi,

Is there any option to use the plugin with server installation of bitbucket?

Regards,
Oleg

**Comment by MichaelRueegg** [comment]
Hi Oleg,

No. But we do provide a commercial Sonar integration for Bitbucket Server: https://marketplace.atlassian.com/plugins/ch.mibex.stash.sonar4stash/server/overview

Hope that helps. If you have questions on how to use that plug-in or what it can do, please do not hesitate to ask.

Best regards,
Michael
