### ISSUE TITLE
Non-maven PHP project hosted on bitbucket

### ISSUE THREAD

**Issue by user102030** [mibexsoftware/sonar-bitbucket-plugin#30]
Hello, 

This might not be an issue but quick question about the plugin. I have a PHP project which is not based on maven, hosted on bitbucket. I do have jenkins job which is building this php project. I have integrated this plugin's config "mvn clean" before build on the job. I do have maven and sonarqube 5.6 configured correctly.  

Here is the error:
_org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory_

Thanks!

**Comment by MichaelRueegg** [comment]
Hi,

When you run a Maven command, it expects that you have a pom.xml file in the current directory (unless you specify an explicit path to it). If you don't want to use Maven with your PHP project, you could use SonarRunner where you don't need a pom.xml file:

    sonar-runner -Dsonar.analysis.mode=issues <other-options>

Best regards,
Michael

**Comment by user102030** [comment]
Hi Michael,

Appreciate your quick reply. I am using sonarqube jenkins plugin which did the job for me. 

Thanks
Abe
