### ISSUE TITLE
PullRequest comment with OAuth got 403

### ISSUE THREAD

**Issue by nfalco79** [mibexsoftware/sonar-bitbucket-plugin#39]
I'm trying to enable sonar4bitbucket when we build pullrequest under Jenkins CI server.

I made some try with API Key and it works but our IT department that handle the organisation accout is not happy of all comment messages. So I would try with OAuth authentication for the our builder account.

There is no some documentation on how to configure OAuth with this plugin, seems there are only 2 property to setup. After googling a lot the most helpful documentation is the comment of class `ch.mibex.bitbucket.sonar.client.AuthenticationFilter.scala`

Than:

1. in bitbucket settings add a customer, this will generate a Key and a Secret
2. also if optional we have to put a callback URL or the sonar plugin fails. I set to https://bitbucket.org/site/oauth2/authorize as described [here](https://developer.atlassian.com/static/bitbucket/concepts/oauth2.html)
3. add pullrequest and repository permission to write (is really needed? Could be called the first time you get deny when you post a comment?)

Now if I use the curl described in your comments all goes right.
```
bash$ curl -v -u "consumerKey:consumerSecret" https://bitbucket.org/site/oauth2/access_token  -d grant_type=client_credentials
```
response
```
{"access_token": "wmUR26aN7IIT3bZOyWHF8O9b77-r3-GG7RdgQs1DVQrQ1D1_Qsfn1a9486L8Eb_A43Z95LnHXW--f2Ei-HI=", "scopes": "pullrequest:write", "expires_in": 3600, "refresh_token": "dHMmFd48ATyffsRbrp", "token_type": "bearer"}
```
```
bash$ curl -v -X POST --data "content=test comment" -H "Authorization: Bearer oauth_token" https://bitbucket.org/api/1.0/repositories/acme/myrepository/pullrequests/1/comments
```
response
```
{"display_name": "R&D Builder", "parent_id": null, "filename_hash": null, "filename": null, "content": "test comment", "username": "builder", "pr_repo": {"owner": "acme", "slug": "myrepository"}, "deleted": false, "comment_id": 31849804, "comparespec": ... "is_repo_owner": false}
```

But if I run sonar analisys with the OAuth properties setup correctly I got the follow error
```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: [sonar4bitbucket] Couldn't fetch logged in user uuid, got status: 403
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.getLoggedInUserUUID(BitbucketClient.scala:268)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.uuid$lzycompute(BitbucketClient.scala:33)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.uuid(BitbucketClient.scala:33)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.ch$mibex$bitbucket$sonar$client$BitbucketClient$$isFromUs$1(BitbucketClient.scala:104)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4$$anonfun$apply$2.apply(BitbucketClient.scala:109)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4$$anonfun$apply$2.apply(BitbucketClient.scala:109)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4.apply(BitbucketClient.scala:109)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient$$anonfun$4.apply(BitbucketClient.scala:108)
	at ch.mibex.bitbucket.sonar.client.BitbucketClient.fetchPage(BitbucketClient.scala:244)
```

it makes a call to register mibexsoftware as OAuth application (I see it in bitbucket) aftee that seems it lookup for all comments in the pull request and matches them against OAuth login but seems to fail.

My expectation is configure OAuth for the builder user that can access the repository and post sonar issues comment under its account instead use the team account.

Can you explain me what's is wrong?

**Comment by nfalco79** [comment]
Bitbucket settings:

![immagine](https://cloud.githubusercontent.com/assets/4160180/23177265/7549db5a-f866-11e6-8e14-9a1987c44575.png)


Sonar properties:

```
[FJ4DEK67WJS5FJB3Q] Running shell script
+ /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarQube_Scanner_2.8/bin/sonar-scanner -Dsonar.host.url=http://jenkins.lan/sonar -Dsonar.login=****** -Dsonar.projectKey=MyTestProject -Dsonar.projectVersion=1.0.0 -Dsonar.analysis.mode=issues -Dsonar.bitbucket.repoSlug=modules.securemail.client -Dsonar.bitbucket.accountName=acme -Dsonar.bitbucket.oauthClientKey=*OAUTH_KEY* -Dsonar.bitbucket.oauthClientSecret=*OAUTH_SECRET* -Dsonar.bitbucket.branchName=feature/pipeline

INFO: Scanner configuration file: /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarQube_Scanner_2.8/conf/sonar-scanner.properties
```

**Comment by sedlak** [comment]
I have very similar issue. Were you able to pass this somehow? 
Thanks

**Comment by mrueegg** [comment]
Hi,

Looking at the provided error message, I think the reason for this is that the "account read" permissions are not granted. This is the minimum amount of permissions for the OAuth consumer:

![min-permissions-bitbucket](https://cloud.githubusercontent.com/assets/206944/23309052/866e8d7e-faad-11e6-873b-a3a6529914d5.png)

We need the write permissions to make pull request comments. If this does not help, could you please run the plug-in with debugging enabled and attach the trace output?

```
mvn sonar:sonar -X -Dsonar.verbose=true ...
```

**Comment by mrueegg** [comment]
By the way, I have to improve the documentation accordingly :-)

**Comment by sedlak** [comment]
Account read permission works for me. 
Thanks a lot

**Comment by mrueegg** [comment]
Perfect, thanks for your feedback. I'll comment that in the documentation.

**Comment by nfalco79** [comment]
Also for me with Account read no more 403

**Comment by xboxsupportchat** [comment]
Every Moment technology has become a new invention, it has been growing day by day, it has been for us to relieve our lifestyle, but if they're having some issue then need support. We all play Games, One of the Game I suggest [Xbox Support](http://xboxsupport.strikingly.com/) their support has been very much effective for help to the consumer.

**Comment by bigpondsupporthelp** [comment]
Every Moment technology has become a new invention, it has been growing day by day, it has been for us to relieve our lifestyle, but if they're having some issue then need support. We all know about Telstra which has been called as Bigpond, It is the basically Australian Mail provider Service. But in case our have some issue overshare so we need support as quickly as possible then we Need to Follow [Bigpond Support](http://bigpondsupporthelp.strikingly.com/) it Helps.  And of course, they are very much supportive. 
I think Bigpond Support will help us with the Matter.

**Comment by windowssupporthelp** [comment]
Every Moment technology has become a new invention, it has been growing day by day, it has been for us to relieve our lifestyle, but if they're having some issue then need support. We all use Windows system software most of the time, So many People having windows in their pc or, laptop, But in case we have some issue over there so we need support as quickly as possible then we Need to Follow [Windows Support](http://www.windowssupport.co/) it Helps.  And of course, they are very much supportive.
