### ISSUE TITLE
Compatibility with Bitbucket Server?

### ISSUE THREAD

**Issue by tknerr** [mibexsoftware/sonar-bitbucket-plugin#40]
I'm aware that mibexsoftware also distributes a plugin to be installed on bitbucket server:
https://marketplace.atlassian.com/plugins/ch.mibex.stash.sonar4stash/server/overview

However, that's a totally different approach and requires you to have admin permissions to install plugins on the server.

I really like the lightweight approach of this plugin here to simply add comments in combination with running sonar-scanner in preview mode. That's exactly what we would need. Just for bitbucket server instead of bitbucket cloud...

I was wondering why the functionality is not there yet. Is it because the REST APIs between bitbucket server and cloud so vastly different?

**Comment by mrueegg** [comment]
The REST API's between the two are quite different, so there would be quite an amount of effort to support Bitbucket Server as well. Also, as we already provide a plug-in for Bitbucket Server, we are unlikely going to support it in this plug-in as well.

I can understand that the lightweight approach is a good fit, but please also consider the advantages you get with the Bitbucket Server plug-in: the integration is better (you also get statistics information for the various Sonar metrics, you have test coverage and code duplication markers, you have merge checks based on metrics, automated branch handling, etc.) and your pull request gets less polluted with comments but instead we show real issue markers in the diff. On the other hand - as you already mentioned - you need to install a plug-in. But please note that you also need to install this plug-in on your SonarQube instance.

Thanks for your understanding.
