### ISSUE TITLE
Does it work with sonar-scanner too?

### ISSUE THREAD

**Issue by tknerr** [mibexsoftware/sonar-bitbucket-plugin#41]
I was wondering whether this plugin needs to be installed on the sonarqube server, or whether it would also work locally with `sonar-scanner`.

As you are using `sonar-runner -Dsonar.analysis.mode=issues ...` on the server, I was wondering if you couldn't use `sonar-scanner -Dsonar.analysis.mode=preview ...` on a CI build node too.

When doing local analysis using `sonar-scanner -Dsonar.analysis.mode=preview ...` (i.e. without uploading results to the sonarqube server), I'm wondering why this plugin needs to be installed on the sonarqube server?

**Comment by mrueegg** [comment]
Hi,

I don't think there is a way of using this plug-in without installing it on the SonarQube server. Are you aware of any SonarQube plug-ins running outside of the SonarQube server?

It shouldn't matter if you are using `sonar-runner` or `sonar-scanner` (I have used both). Also, both modes `issues` and `preview` are supported. You can just not use it in a "normal" / persistent mode.

Does that answer you question?

**Comment by tknerr** [comment]
I just recently learned that sonarqube plugins are always stored on the
server, and then downloaded via sonar-scanner...

So it's all clear now. Thanks!

Am 23.03.2017 2:21 nachm. schrieb "Michael Rüegg" <notifications@github.com

**Comment by mrueegg** [comment]
You're welcome!
