### ISSUE TITLE
Does sonar-bitbucket-plugin work for non-Maven project?

### ISSUE THREAD

**Issue by madhurilalit** [mibexsoftware/sonar-bitbucket-plugin#47]
### Expected Behavior

EDF client to add the following SonarQube plugin for their application. This Sonarqube plug-in creates pull request comments for issues found in your Bitbucket Cloud pull requests. It creates a summary of the found issues as a global pull request comment. Its a non-maven project.

### Actual Behavior

Sonar report & comments should be visible to source code file in Bit-bucket however this is not happening right now. We need to check if plugin supports non-maven projects also.

### Plug-in version, SonarQube version, CI system, build type

https://github.com/mibexsoftware/sonar-bitbucket-plugin

I am using sonar-bitbucket-plugin for my non Maven project. I have done below configuration in Jenkins job' "SONAR Scanner" text box:

sonar.analysis.mode=issues
sonar.bitbucket.login=test
sonar.bitbucket.password=$PASSWD
sonar.bitbucket.repository=https://$repo_url/pullrequests/$PULL_REQUEST_ID
sonar.bitbucket.pullRequestId=$PULL_REQUEST_ID
sonar.bitbucket.minSeverity=MAJOR
sonar.bitbucket.buildStatusEnabled=true

Kindly confirm if this plugin can be used in non-Maven project and if yes, what is the setting that I am missing.

**Comment by mrueegg** [comment]
Hi,

Thanks for your feedback. The plug-in also works in a non-Maven build. We tested it e.g. with SonarRunner. You should use the same parameters as for the Maven build, which we describe in our README here: https://github.com/mibexsoftware/sonar-bitbucket-plugin#configuration-for-bamboo-with-maven

Hope this helps. Otherwise, please let me know.

Best regards,
Michael

**Comment by madhurilalit** [comment]
HI Michael,

Please confirm what to provide for below field, i am unable to understand that from description given on the same page. An example for each of these field would be helpful:

 -Dsonar.bitbucket.repoSlug=YOUR_BITBUCKET_REPO_SLUG \
     -Dsonar.bitbucket.accountName=YOUR_BITBUCKET_ACCOUNT_NAME \
     -Dsonar.bitbucket.teamName=YOUR_BITBUCKET_TEAM_ID \
     -Dsonar.bitbucket.apiKey=YOUR_BITBUCKET_API_KEY \

Also please confirm if i can use all of these properties as part of Execute Sonarqube scanner plugin in Jenkins. Please confirm if any changes needs to be made in properties mentioned at https://github.com/mibexsoftware/sonar-bitbucket-plugin#configuration-for-bamboo-with-maven.

Thanks
Madhuri

**Comment by mrueegg** [comment]
Hi,

The account name and the repository slug are part of your Bitbucket repository URL: https://bitbucket.org/ACCOUNT_NAME/REPOSITORY_SLUG.

For authentication, you can either use your personal user account or a team (depending if you want that the creator of the pull request comment for found issues is your user or a team account). For the team, you have to use the two options "sonar.bitbucket.teamName" and "sonar.bitbucket.apiKey". You can get/create the API key under your Bitbucket team account settings.

Hope this helps.

Best regards,
Michael

**Comment by sivakumarsakkarai** [comment]
Hi I have sonarqube server on AWS and i am planning to integrate sonarqube with bitbucket cloud account for code analysis( 1st we are planning to verify the code quality)  and then it will move to jenkins, 

we are not able to get Idea to integrate the sonar with Bitbucket pipeline. Kindly help me to find the solution to this
