### ISSUE TITLE
Private BitBucket repository throw unauthorized exception.

### ISSUE THREAD

**Issue by 3qn** [mibexsoftware/sonar-bitbucket-plugin#57]
### Expected Behavior

Should post comments in BitBucket, can i set url for private bitbucket repository ?

### Actual Behavior

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project cardinality: GET https://bitbucket.org/api/2.0/repositories/jenkins/test_project/pullrequests?page=1&pagelen=50&state=OPEN returned a response status of 401 Unauthorized -> [Help 1]

**Comment by mrueegg** [comment]
Actually, you should be able to use a private repository. What kind of authentication are you using? Team API key, user API key or OAuth?

**Comment by 3qn** [comment]
Im not sure in our version BitBucket i cant find some thing like team only group and i think it is feature from cloud version. No i don't use any authentication 

maven sonar:sonar --batch-mode --errors  
-Dsonar.bitbucket.repoSlug=projectName  
-Dsonar.bitbucket.accountName=jenkins  
-Dsonar.bitbucket.teamName=cardinality  
-Dsonar.bitbucket.apiKey=2617c7ed167b2d99b74add7ca1b04317f3043ed9    <- from sonarQube project properties
-Dsonar.bitbucket.branchName=$GIT_BRANCH  
-Dsonar.host.url=http://docker-container-01:9000/  
-Dsonar.login=admin 
-Dsonar.password=admin  
-Dsonar.analysis.mode=issues 
-Dsonar.bitbucket.buildStatusEnabled=false 
-Dsonar.bitbucket.approvalFeatureEnabled=false

**Comment by mrueegg** [comment]
Thanks for your feedback. Please note that

```
-Dsonar.bitbucket.apiKey=
```

must not be set to the Sonar API key, but to the Bitbucket API key for the team `cardinality`.

**Comment by 3qn** [comment]
Bitbucket Server don have feature Team work.
