### ISSUE TITLE
Use Sonarqube quality gate to approve PR

### ISSUE THREAD

**Issue by lukasz-czarnecki-ynd** [mibexsoftware/sonar-bitbucket-plugin#59]
### Expected Behavior

Plugin should check which quality gate is being used in Sonarqube for particular project and determine the PR approval based its settings. As a fallback mechanism some plugin configuration that would allow to change the conditions of approval would also do the job.

### Actual Behavior

Currently plugin approves the PR if there are no brockers or crits. This causing the situation where we have approved PR and build breaks after merge, where full sonarqube analysis is being performed. This greatly interrupts our development process.

### Plug-in version, SonarQube version, CI system, build type

Latest plugin version, Sonarqube 6.4, Jenkins, gradle

**Comment by lukasz-czarnecki-ynd** [comment]
I think `sonar.bitbucket.minApprovalSeverity=[INFO|MINOR|MAJOR|CRITICAL|BLOCKER]` option would be enough for now.

@mrueegg WDYT?

**Comment by nfalco79** [comment]
I'm agree with @lukasz-czarnecki-ynd . Also in our case I notice that the plugin approves the PR also if there are MAJOR issue on the PR. I would like configure the plugin to configure this behavior and avoid custom build

**Comment by mrueegg** [comment]
@lukasz-czarnecki-ynd Please excuse my late response. I absolutely agree that this should be configurable. As soon as the remaining issues in pull request #54 are fixed, I'm happy to merge it.
