### ISSUE TITLE
Send report to SonarQuobe

### ISSUE THREAD

**Issue by zakrush** [mibexsoftware/sonar-bitbucket-plugin#66]
### Expected Behavior
After Pull request I'll get comment at the bitbucket and result of scan sent to the server SonarQube.

### Actual Behavior

After scan I didn't see any changes to project.

### Plug-in version, SonarQube version, CI system, build type
SonarQube v 6.7.0.33306
Bitbucket for Sonar 1.2.1
Jenkins 2.73.3

Config of sonar-scanner

```
sonar.projectKey=timebook_psr
sonar.projectName=timebook_psr

sonar.projectVersion=1.0
sonar.bitbucket.repoSlug=*****
sonar.bitbucket.accountName=*******
sonar.bitbucket.branchName=${BRANCH_NAME}
sonar.bitbucket.oauthClientKey=********
sonar.bitbucket.oauthClientSecret=********
sonar.analysis.mode=issues
sonar.bitbucket.minSeverity=INFO
```

Jenkins command line, I didn't see "sent to server" line. 

> 0:20:21 INFO: ANALYSIS SUCCESSFUL
>10:20:22 INFO: Executing post-job Sonar Plug-in for Bitbucket Cloud
>10:20:24 INFO: [sonar4bitbucket] Plug-in is active and will analyze pull request with #2487...
>10:20:29 INFO: Task total time: 21.100 s
>10:20:29 INFO: ------------------------------------------------------------------------
>10:20:29 INFO: EXECUTION SUCCESS
>10:20:29 INFO: ------------------------------------------------------------------------
>10:20:29 INFO: Total time: 22.264s
>10:20:29 INFO: Final Memory: 60M/559M
>10:20:29 INFO: ------------------------------------------------------------------------
>10:20:30 Finished: SUCCESS

**Comment by mrueegg** [comment]
Hi,

With analysis mode "issues" (sonar.analysis.mode=issues) the analysis results are not persisted on SonarQube. This mode is for analyzing pull requests only. Hope that helps. Otherwise, please let me know.

Best regards,
Michael

**Comment by zakrush** [comment]
I can't understand in what diff issue and preview mode. I need that comments from Sonar will not delete after second pull request.
Thank you.
