### ISSUE TITLE
Release 1.2.2 miss of the binary (jar) file

### ISSUE THREAD

**Issue by nfalco79** [mibexsoftware/sonar-bitbucket-plugin#69]
There is no binary file for version 1.2.2 in the release page

**Comment by kmalmur** [comment]
the same for 1.2.3

**Comment by nfalco79** [comment]
No luck

**Comment by arobinson-alcumusgroup** [comment]
Hi @mrueegg are there any plans to provide the jar file for release 1.2.3?

**Comment by vseveryn** [comment]
meanwhile 1.2.3 can be uploaded [here](https://bitbucket.org/vseveryn/heroku-buildpack-sonarqube-bitbucket/downloads/sonar-bitbucket-plugin-1.2.3.jar)

**Comment by ilyar** [comment]
```bash
git clone git@github.com:mibexsoftware/sonar-bitbucket-plugin.git
docker run -it --rm -w /opt/maven \
   -v $PWD:/opt/maven \
   -v $HOME/.m2:/root/.m2 \
   maven:3.3-jdk-8 \
   mvn clean install
```
https://github.com/mibexsoftware/sonar-bitbucket-plugin/pull/85

**Comment by nfalco79** [comment]
Seems there is not avaiability for next releases to be published in github
