### ISSUE TITLE
Issues mode is deprecated

### ISSUE THREAD

**Issue by Fraserhardy** [mibexsoftware/sonar-bitbucket-plugin#81]
### Actual Behavior
We're seeing this line in our logs: 

WARN: The use of the issues mode (sonar.analysis.mode=issues) is deprecated. This mode will be dropped in the future.

What mode should we be running in for sonar-bitbucket plugin to continue working? 

### Plug-in version, SonarQube version, CI system, build type

SonarQube Scanner 3.0.3.778
SonarQube: Version 6.7.1 (build 35068)

**Comment by gvasquez-waypoint** [comment]
Same here on Version 6.7.3 (build 38370)

**Comment by ilyar** [comment]
Same here on Version 7.1 (build 11001)

**Comment by mrueegg** [comment]
Hi all,

We analyzed this and unfortunately, we cannot support SonarQube versions >= 7.7 anymore in our Bitbucket Cloud app because of the removed issues/preview mode and because there is no replacement.

Thank you for your understanding.

Best regards,
Michael

**Comment by Fraserhardy** [comment]
Do you have any more information from SonarQube on this? What is the proposed solution to continue having a workflow where our PR's have comments applied based on the SonarScanner results? 

I assume this doesn't just affect Bitbucket but other integrations too?
